version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: financeiradb
    restart: no
    environment:
      POSTGRES_DB: financeiradb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - financeira-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - financeira-network
    depends_on:
      - postgres

  financeira-app:
    build: .
    container_name: financeira-app
    restart: always
    environment:
      DATASOURCE_URL: "Host=postgres;Port=5436;Database=financeiradb;Username=postgres;Password=postgres"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
    networks:
      - financeira-network
    depends_on:
      - postgres

networks:
  financeira-network:
    driver: bridge

volumes:
  postgres_data:
